package enums

type Response int

const (
	OK Response = iota
	UNKNOWN_COMMAND
	INVALID_ARGS
	PONG
	ERROR
	INVALID_PATH_ERR
	INVALID_TYPE_ERR
	TABLE_NOT_EXISTS
	TABLE_ALREADY_EXISTS
	CHANNEL_NOT_EXISTS
	CHANNEL_ALREADY_EXISTS
)

var MESSAGE_RESPONSE_MAP = map[Response]string{
	OK:                     "OK",
	UNKNOWN_COMMAND:        "UNKOWN_COMMAND",
	INVALID_ARGS:           "INVALID_ARGS",
	PONG:                   "PONG",
	ERROR:                  "ERROR",
	INVALID_PATH_ERR:       "INVALID_JSON_PATH",
	INVALID_TYPE_ERR:       "INVALID_TYPE_ERR",
	TABLE_NOT_EXISTS:       "TABLE_NOT_EXISTS",
	TABLE_ALREADY_EXISTS:   "TABLE_ALREADY_EXISTS",
	CHANNEL_NOT_EXISTS:     "CHANNEL_NOT_EXISTS",
	CHANNEL_ALREADY_EXISTS: "CHANNEL_ALREADY_EXISTS",
}

func GetResponseMessage(resp Response) string {
	return MESSAGE_RESPONSE_MAP[resp]
}
